
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://cobblethingstogether.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: #/personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "HyperChiicken"
title: "{ HyperChiicken }"
description: "HyperChiicken's little coop. A blog and website containing random things I cobbled together."
keywords: "hyperchiicken, hyper, chiicken, personal, prototype, projects"
favicon: "/img/black.ico"

################
# Header layout #
################

black-favicon: "/img/white.png"

background-img: "../img/bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "I cobble things together :]"
# - text: "Where’s your will to be weird?"

me-img: "/img/logo.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/hyperchiicken.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False
enable-comments: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: True
tumblr-share: False
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/to_mars.jpg"
    date: "November 2019 - Present"
    description: "Venturing the unknown!"
  - image: "/img/timeline/kojima_arm.jpg"
    date: "March 2019"
    description: "Started creating art and prototypes :]"
  - image: "/img/timeline/troubled.jpg"
    date: "February 2019"
    description: "Soul-searching month..."
  - image: "/img/timeline/onepunch.jpg"
    date: "January 2019"
    description: "Diagnosed with advanced glaucoma and vasculitis"
  - image: "/img/timeline/koro-sensei.jpg"
    date: "December 2018"
    description: "Freed from the shackles of Academia!"

# First image of the Timeline

timeline-img: "/img/timeline/chicken_or_the_egg.jpg"
 
###########
# Contact #
###########

email: "hyperchiicken@cobblethingstogether.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: #"BLUUUURB"
author_blurb_image: #"/img/author.png"

##################
# Social Buttons #
##################

# The title is tied to the icon found in font-awesome 5.11.0. Check the icons available on https://fontawesome.com/
# To use the desired icon, copy and paste the icon's class ex. class="fas fa-robot" put title: "fas fa-robot"

social:
  - title: "fab fa-instagram"
    url: "https://instagram.com/hyperchiicken"
  - title: "fab fa-github"
    url: "https://github.com/hyperchiicken"
  - title: "fas fa-hospital-symbol"
    url: "https://www.hackster.io/HyperChiicken/"
  - title: "fas fa-robot"
    url: "https://www.instructables.com/member/HyperChiicken/"
  - title: "fab fa-itch-io"
    url: "https://hyperchiicken.itch.io/"
  - title: "fab fa-youtube"
    url: "https://www.youtube.com/channel/UCz5rKw3tF71ck_72kDLZsfg"
     
############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: hyperchiicken
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
